name: make updates

on:
  push:
  pull_request:

jobs:
  centos6:
    runs-on: ubuntu-latest
    steps:
    - name: Check for updates
      run: |
        mkdir ~/.ssh
        echo "${GIT_SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        export GIT_SSH_COMMAND="ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes -o StrictHostKeyChecking=no"
        git config --global user.email "me@harmenstoppels.nl"
        git config --global user.name "Harmen Stoppels"
        git clone https://github.com/spack/spack.git
        cd spack
        git checkout -b some-updates
        timeout 5m ./bin/spack python ../update.py || true
        git remote add mirror git@github.com:haampie-spack/spack.git
        git push -f mirror some-updates
      env:
        GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_KEY }}


